version: '3.8'

services:
  hugo-builder:
    image: hugomods/hugo:exts
    container_name: pipun-hugo-builder
    working_dir: /src
    volumes:
      - .:/src
    command: hugo --minify
    profiles:
      - build
