baseURL = 'https://pipun.pro/'
languageCode = 'ru-RU'
title = 'Pipun VPN'

[params]
  description = 'Полноценная работа ваших сервисов'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
